correct `decrypt`/`encrypt` to `-d`/`-e` in README
getsops/sops pull request #1494
Opened 2024-04-23 22:09 UTC by jmhodges

The README described the use of `sops decrypt` and `sops encrypt` commands that no longer exist in modern versions.

The correct commands seem to be `sops -d` and `sops -e`.

I ran into this while trying to get the `git diff`ing working as described in this doc.

2024-04-24 05:22 UTC, felixfontein requested changes
The README refers to the version in the `main` branch, not to any yet released version.

2024-05-16 16:44 UTC, jmhodges commented
What is the actually accurate documentation link, then? Folks have been linking to this and leading folks astray

2024-05-16 17:41 UTC, felixfontein commented
The README for 3.8.1 is at https://github.com/getsops/sops/blob/v3.8.1/README.rst. Right now there is unfortunately no way to always view the docs for the latest released version, you have to use the README.rst from the corresponding tag...

2024-08-13 08:37 UTC, felixfontein commented
Closing since 3.9.0 has been released. Thanks for your contribution!

2024-08-13 08:37 UTC, closed without merging