Allow to encrypt and decrypt from stdin
getsops/sops pull request #1690
Opened 2024-12-01 12:40 UTC by felixfontein

Allows to encrypt/decrpyt from stdin by providing no input filename to the `encrpyt` and `decrpyt` commands. For `encrypt`, `--filename-override` must be provided in that case to be able to select the proper creation rule.

Fixes #739
Ref: #1104

2025-03-01 23:27 UTC, sabre1041 requested changes
Functionality works as described. A few minor items in the README

2025-03-01 23:27 UTC, sabre1041 commented on README.rst
> +``sops`` determines the input and output format from the provided filename, which is the empty string here, and
What is the empty string in this case?

2025-03-02 07:20 UTC, felixfontein commented on README.rst
> +``sops`` determines the input and output format from the provided filename, which is the empty string here, and
Hmm, that wasn't a good way to describe it :) Internally the filename will be the empty string, but that isn't very helpful to most users. I've rewritten the whole decryption part in c67caf020644718f67a4b8b8e6d7f1b75f083f90, I hope it's better now.

2025-03-02 19:41 UTC, sabre1041 commented on README.rst
> +``sops`` determines the input and output format from the provided filename, which is the empty string here, and
much clearer!

2025-03-02 20:59 UTC, merged

2025-03-02 20:59 UTC, felixfontein commented
@sabre1041 thanks for reviewing!